"""Add soft delete support (deleted_at column)

Revision ID: 47d65459653b
Revises: c4e8f9a2b3d1
Create Date: 2025-11-10 22:25:19.572755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d65459653b'
down_revision = 'c4e8f9a2b3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_shopping_list_items_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_shopping_lists_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_lists_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_list_items_deleted_at'))
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
