"""add indexes to foreign keys for performance optimization

Revision ID: aace83301714
Revises: d5f9b3a8c2e7
Create Date: 2025-11-11 12:33:47.984905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aace83301714'
down_revision = 'd5f9b3a8c2e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_list_items_shopping_list_id'), ['shopping_list_id'], unique=False)

    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_lists_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_lists_user_id'))

    with op.batch_alter_table('shopping_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_list_items_shopping_list_id'))

    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_user_id'))

    # ### end Alembic commands ###
